version: 0.0
os: linux
files:
  - source: /
    destination: /opt/report-engine
hooks:
  ApplicationStop:
    - location: deploy/stop.sh
      timeout: 60
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 60
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 60
  ApplicationStart:
    - location: deploy/start.sh
      timeout: 60
  ValidateService:
    - location: deploy/basic_health_check.sh