version: 0.0
os: linux
files:
  - source: /
    destination: /opt/report-engine
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 60
  BeforeInstall:
    - location: before_install.sh
      timeout: 60
  AfterInstall:
    - location: after_install.sh
      timeout: 60
  ApplicationStart:
    - location: start.sh
      timeout: 60
  ValidateService:
    - location: basic_health_check.sh